{{- if .Values.rbac.create }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "server-components-demo.name" . }}-clusterrolebinding
  labels:
    app.kubernetes.io/name: {{ include "server-components-demo.name" . }}
    helm.sh/chart: {{ include "server-components-demo.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- with .Values.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
subjects:
  - kind: ServiceAccount
    name: {{ include "server-components-demo.name" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "server-components-demo.name" . }}-clusterrole
  apiGroup: rbac.authorization.k8s.io
{{- end}}