apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "server-components-demo.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "server-components-demo.name" . }}
    helm.sh/chart: {{ include "server-components-demo.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    release: "prometheus"
{{- with .Values.service.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
{{- end }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "server-components-demo.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  endpoints:
  - port: http