name: Deploy specific image

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      imageTag:
        description: 'Image tag'
        required: true
        default: 'latest'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

    # KUBE_CONFIG_DATA is a base64-encoded kubeconfig file with credentials for Kubernetes to access the cluster. You can get it by running the following command:
    # cat $HOME/.kube/config | base64
    - name: Helm deploy
      uses: koslib/helm-eks-action@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      with:
        command: helm upgrade -i server-components-demo ./helm --set image.tag=${{ github.event.inputs.imageTag }}

    - name: Verify deployment
      uses: qazz92/kubectl@1.0.3
      env:
        kube_confg_data: ${{ secrets.KUBE_CONFIG_DATA }}
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_DEFAULT_REGION }}
      with:
        args: rollout status deployment/server-components-demo
