name: Take a snapshot to push an image tag

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      sourceRef:
        description: 'Git ref to pull'
        required: true
        default: 'main'
      imageTag:
        description: 'Image tag'
        required: true

jobs:
  buildAndPush:
    name: Build and Push
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.sourceRef }}
      
    - uses: cschleiden/replace-tokens@v1
      with:
        files: '["credentials.js"]'
      env:
        DB_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
        
    - name: Docker Login
      uses: docker/login-action@v1.8.0
      with:
        registry: ghcr.io
        username: vxavictor513
        password: ${{ secrets.GHCR_TOKEN }}
        logout: true  

    # Build the Docker image
    - name: Build
      run: |-
        docker build \
          --tag "ghcr.io/vxavictor513/server-components-demo:${{ github.event.inputs.imageTag }}" \
          .

    # Push the Docker image to GitHub Container Registry
    - name: Publish
      run: |-
        docker push "ghcr.io/vxavictor513/server-components-demo:${{ github.event.inputs.imageTag }}"
